"""
Hash file format handling and operations
"""

import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass

from .file_scanner import FileInfo
from .hash_algorithms import HashAlgorithm


@dataclass
class HashEntry:
    """Represents a single entry in a hash file"""
    file_hash: str
    other_hash: str
    directory: str
    filename: str
    file_size: int
    inode: int
    mtime: int
    is_symlink: bool = False


class HashFile:
    """Handles reading and writing hash files"""
    
    def __init__(self, file_path: Path):
        self.file_path = file_path
        self.metadata = {}
        self.entries: List[HashEntry] = []
    
    def write_metadata_header(self, base_dir: Path):
        """Write metadata header to hash file"""
        from .file_scanner import get_system_info
        
        system_info = get_system_info()
        
        self.metadata = {
            'version': '2.0.0',
            'machine': system_info['hostname'],
            'base_directory': str(base_dir),
            'user': system_info['username'],
            'generated': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
    
    def write_header(self, base_dir: Path):
        """Write header section to file"""
        self.write_metadata_header(base_dir)
        
        with open(self.file_path, 'w') as f:
            # Write metadata header
            f.write(f"# Generated by filehasher v{self.metadata['version']}\n")
            f.write(f"# Machine: {self.metadata['machine']}\n")
            f.write(f"# Base directory: {self.metadata['base_directory']}\n")
            f.write(f"# User: {self.metadata['user']}\n")
            f.write(f"# Generated: {self.metadata['generated']}\n")
    
    def add_entry(self, entry: HashEntry, algorithm_name: str = None, write_to_file: bool = True):
        """Add a hash entry to the file"""
        self.entries.append(entry)
        
        if write_to_file:
            # Append to file
            mode = 'w' if not self.file_path.exists() else 'a'
            
            with open(self.file_path, mode) as f:
                if entry.is_symlink:
                    # Write symlink as commented line
                    line = f"# SYMLINK|{entry.directory}|{entry.filename}|{entry.file_size}|{entry.inode}|{entry.mtime}\n"
                else:
                    # Write regular entry with algorithm prefix if specified
                    if algorithm_name and algorithm_name.lower() != 'md5':
                        hash_with_algo = f"{algorithm_name.upper()}:{entry.file_hash}"
                    else:
                        hash_with_algo = entry.file_hash  # MD5 is default, no prefix
                    
                    line = f"{hash_with_algo}|{entry.other_hash}|{entry.directory}|{entry.filename}|{entry.file_size}|{entry.inode}|{entry.mtime}\n"
                
                f.write(line)
    
    def write_all_entries(self, algorithm_name: str = None):
        """Write all entries to file (useful for updating)"""
        with open(self.file_path, 'w') as f:
            # Write header
            f.write(f"# Generated by filehasher v{self.metadata['version']}\n")
            f.write(f"# Machine: {self.metadata['machine']}\n")
            f.write(f"# Base directory: {self.metadata['base_directory']}\n")
            f.write(f"# User: {self.metadata['user']}\n")
            f.write(f"# Generated: {self.metadata['generated']}\n")
            
            # Write all entries
            for entry in self.entries:
                if entry.is_symlink:
                    line = f"# SYMLINK|{entry.directory}|{entry.filename}|{entry.file_size}|{entry.inode}|{entry.mtime}\n"
                else:
                    if algorithm_name and algorithm_name.lower() != 'md5':
                        hash_with_algo = f"{algorithm_name.upper()}:{entry.file_hash}"
                    else:
                        hash_with_algo = entry.file_hash
                    
                    line = f"{hash_with_algo}|{entry.other_hash}|{entry.directory}|{entry.filename}|{entry.file_size}|{entry.inode}|{entry.mtime}\n"
                
                f.write(line)
    
    def read_entries(self) -> List[HashEntry]:
        """Read all entries from hash file, skipping comments"""
        self.entries = []
        
        if not self.file_path.exists():
            return self.entries
        
        with open(self.file_path, 'r') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                
                # Parse metadata from comment lines
                if line.startswith('#'):
                    if line.startswith('# Generated by filehasher v'):
                        self.metadata['version'] = line.split('v')[1]
                    elif line.startswith('# Machine: '):
                        self.metadata['machine'] = line[10:]
                    elif line.startswith('# Base directory: '):
                        self.metadata['base_directory'] = line[18:]
                    elif line.startswith('# User: '):
                        self.metadata['user'] = line[8:]
                    elif line.startswith('# Generated: '):
                        self.metadata['generated'] = line[13:]
                    continue
                
                # Skip empty lines
                if not line:
                    continue
                
                # Skip lines that don't look like data (no pipe separators)
                if '|' not in line:
                    continue
                
                try:
                    entry = self._parse_line(line)
                    self.entries.append(entry)
                except ValueError as e:
                    print(f"Warning: Skipping invalid line {line_num} in {self.file_path}: {e}")
                    continue
        
        return self.entries
    
    def _parse_line(self, line: str) -> HashEntry:
        """Parse a single line from hash file"""
        parts = line.split('|')
        
        if len(parts) != 7:
            raise ValueError(f"Invalid line format, expected 7 parts, got {len(parts)}")
        
        # Parse hash (may include algorithm prefix)
        file_hash = parts[0]
        if ':' in file_hash:
            # Algorithm:hash format
            algorithm, hash_value = file_hash.split(':', 1)
            file_hash = hash_value  # Extract just the hash part
        # If no ':' present, assume MD5 for backwards compatibility
        
        return HashEntry(
            file_hash=file_hash,
            other_hash=parts[1],
            directory=parts[2],
            filename=parts[3],
            file_size=int(parts[4]),
            inode=int(parts[5]),
            mtime=int(parts[6]),
            is_symlink=False  # Regular entries are not symlinks
        )
    
    def find_duplicates(self) -> Dict[str, List[HashEntry]]:
        """Find duplicate files based on hash values"""
        hash_groups = {}
        
        for entry in self.entries:
            if entry.is_symlink:
                continue  # Skip symlinks
            
            if entry.file_hash not in hash_groups:
                hash_groups[entry.file_hash] = []
            
            hash_groups[entry.file_hash].append(entry)
        
        # Return only groups with duplicates
        return {h: entries for h, entries in hash_groups.items() if len(entries) > 1}
    
    def compare_with(self, other: 'HashFile') -> Dict[str, List[HashEntry]]:
        """Compare this hash file with another to find matching hashes"""
        # Create hash lookup for other file
        other_hashes = {}
        for entry in other.entries:
            if not entry.is_symlink:
                other_hashes[entry.file_hash] = entry
        
        # Find matches
        matches = {}
        for entry in self.entries:
            if entry.is_symlink:
                continue
            
            if entry.file_hash in other_hashes:
                other_entry = other_hashes[entry.file_hash]
                key = entry.file_hash
                if key not in matches:
                    matches[key] = []
                matches[key].extend([entry, other_entry])
        
        return matches
    
    def get_existing_entry(self, relative_path: Path) -> Optional[HashEntry]:
        """Get existing entry for a file path"""
        for entry in self.entries:
            entry_path = Path(entry.directory) / entry.filename
            if entry_path == relative_path:
                return entry
        return None
    
    def needs_update(self, file_info: FileInfo) -> bool:
        """Check if a file needs hash update based on modification time"""
        existing_entry = self.get_existing_entry(file_info.relative_path)
        if existing_entry is None:
            return True  # File not in hash file, needs to be added
        
        # Check if modification time has changed
        return existing_entry.mtime != file_info.mtime
