"""
Hash file format handling for reading and writing .hashes files
"""

import os
import socket
import getpass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Set
from dataclasses import dataclass
import logging

try:
    from .hash_algorithms import HashAlgorithm, HashProcessor
    from .file_scanner import FileInfo
except ImportError:
    from hash_algorithms import HashAlgorithm, HashProcessor
    from file_scanner import FileInfo

logger = logging.getLogger(__name__)


@dataclass
class HashEntry:
    """Represents a single hash file entry"""
    primary_hash: str
    secondary_hash: str
    directory: str
    filename: str
    size: int
    inode: int
    mtime: float
    is_symlink: bool = False
    is_comment: bool = False
    
    @property
    def relative_path(self) -> str:
        """Get relative path as string"""
        if self.directory == '.':
            return self.filename
        return f"{self.directory}/{self.filename}"
    
    @property
    def full_path(self) -> Path:
        """Get full path (requires base directory context)"""
        # This would need base directory context to be meaningful
        return Path(self.relative_path)
    
    def to_line(self) -> str:
        """Convert to hash file line format"""
        if self.is_comment:
            return f"# {self.primary_hash}"
        elif self.is_symlink:
            return f"# SYMLINK|{self.directory}|{self.filename}|{self.size}|{self.inode}|{int(self.mtime)}"
        else:
            return f"{self.primary_hash}|{self.secondary_hash}|{self.directory}|{self.filename}|{self.size}|{self.inode}|{int(self.mtime)}"


@dataclass
class HashFileHeader:
    """Metadata header for hash files"""
    version: str
    machine: str
    base_directory: str
    user: str
    generated: datetime
    algorithm: Optional[str] = None
    
    def to_lines(self) -> List[str]:
        """Convert header to comment lines"""
        lines = [
            f"# Generated by filehasher {self.version}",
            f"# Machine: {self.machine}",
            f"# Base directory: {self.base_directory}",
            f"# User: {self.user}",
            f"# Generated: {self.generated.strftime('%Y-%m-%d %H:%M:%S')}"
        ]
        
        if self.algorithm:
            lines.append(f"# Algorithm: {self.algorithm}")
        
        return lines


class HashFile:
    """Handles reading and writing hash files"""
    
    def __init__(self, file_path: Path):
        self.file_path = Path(file_path)
        self.header: Optional[HashFileHeader] = None
        self.entries: List[HashEntry] = []
        self._algorithm: Optional[HashAlgorithm] = None
    
    def read(self) -> List[HashEntry]:
        """
        Read hash file and parse entries
        
        Returns:
            List of HashEntry objects
        """
        if not self.file_path.exists():
            logger.warning(f"Hash file does not exist: {self.file_path}")
            return []
        
        self.entries.clear()
        self.header = None
        
        try:
            with open(self.file_path, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            header_lines = []
            data_lines = []
            
            # Separate header and data lines
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                
                if line.startswith('#'):
                    header_lines.append(line[1:].strip())  # Remove #
                else:
                    data_lines.append(line)
            
            # Parse header
            if header_lines:
                self.header = self._parse_header(header_lines)
                self._detect_algorithm_from_entries(data_lines)
            
            # Parse data entries
            for line in data_lines:
                entry = self._parse_entry_line(line)
                if entry:
                    self.entries.append(entry)
            
            logger.info(f"Read {len(self.entries)} entries from {self.file_path}")
            return self.entries.copy()
            
        except Exception as e:
            logger.error(f"Error reading hash file {self.file_path}: {e}")
            raise
    
    def _parse_header(self, header_lines: List[str]) -> HashFileHeader:
        """Parse header lines into HashFileHeader object"""
        header_data = {}
        
        for line in header_lines:
            if ':' in line:
                key, value = line.split(':', 1)
                key = key.strip().lower().replace(' ', '_')
                value = value.strip()
                header_data[key] = value
        
        # Parse generation time
        generated = datetime.now()
        if 'generated' in header_data:
            try:
                generated = datetime.strptime(header_data['generated'], '%Y-%m-%d %H:%M:%S')
            except ValueError:
                pass
        
        return HashFileHeader(
            version=header_data.get('generated_by_filehasher', 'unknown').replace('filehasher ', ''),
            machine=header_data.get('machine', 'unknown'),
            base_directory=header_data.get('base_directory', 'unknown'),
            user=header_data.get('user', 'unknown'),
            generated=generated,
            algorithm=header_data.get('algorithm')
        )
    
    def _detect_algorithm_from_entries(self, data_lines: List[str]):
        """Detect algorithm from data entries"""
        for line in data_lines[:10]:  # Check first 10 lines
            if '|' in line:
                parts = line.split('|')
                if len(parts) >= 1:
                    hash_part = parts[0]
                    if ':' in hash_part:
                        algorithm_str = hash_part.split(':', 1)[0].lower()
                        try:
                            self._algorithm = HashAlgorithm(algorithm_str)
                            break
                        except ValueError:
                            continue
        
        # Default to MD5 if no algorithm detected
        if self._algorithm is None:
            self._algorithm = HashAlgorithm.MD5
    
    def _parse_entry_line(self, line: str) -> Optional[HashEntry]:
        """Parse a single hash file entry line"""
        try:
            parts = line.split('|')
            
            if len(parts) < 6:
                logger.warning(f"Invalid entry line (too few parts): {line}")
                return None
            
            # Handle symlinks (commented lines)
            if line.startswith('# SYMLINK'):
                return HashEntry(
                    primary_hash="",
                    secondary_hash="",
                    directory=parts[1] if len(parts) > 1 else '.',
                    filename=parts[2] if len(parts) > 2 else '',
                    size=int(parts[3]) if len(parts) > 3 and parts[3].isdigit() else 0,
                    inode=int(parts[4]) if len(parts) > 4 and parts[4].isdigit() else 0,
                    mtime=float(parts[5]) if len(parts) > 5 and parts[5].isdigit() else 0,
                    is_symlink=True,
                    is_comment=True
                )
            
            # Regular entry
            return HashEntry(
                primary_hash=parts[0],
                secondary_hash=parts[1] if len(parts) > 1 else '',
                directory=parts[2] if len(parts) > 2 else '.',
                filename=parts[3] if len(parts) > 3 else '',
                size=int(parts[4]) if len(parts) > 4 and parts[4].isdigit() else 0,
                inode=int(parts[5]) if len(parts) > 5 and parts[5].isdigit() else 0,
                mtime=float(parts[6]) if len(parts) > 6 and parts[6].isdigit() else 0
            )
            
        except Exception as e:
            logger.warning(f"Error parsing entry line: {line} - {e}")
            return None
    
    def write(self, entries: List[HashEntry], base_directory: Path, 
              algorithm: HashAlgorithm, update_mode: bool = False):
        """
        Write hash file with entries
        
        Args:
            entries: List of HashEntry objects
            base_directory: Base directory for relative paths
            algorithm: Hash algorithm used
            update_mode: If True, merge with existing entries
        """
        # Read existing entries if in update mode
        existing_entries = {}
        if update_mode and self.file_path.exists():
            self.read()
            existing_entries = {entry.relative_path: entry for entry in self.entries}
        
        # Merge entries
        if update_mode:
            # Update existing entries with new ones
            for entry in entries:
                existing_entries[entry.relative_path] = entry
            entries = list(existing_entries.values())
        
        # Create header
        self.header = HashFileHeader(
            version="2.0.0",
            machine=socket.gethostname(),
            base_directory=str(base_directory.resolve()),
            user=getpass.getuser(),
            generated=datetime.now(),
            algorithm=algorithm.value
        )
        
        self.entries = entries
        self._algorithm = algorithm
        
        # Write file
        try:
            with open(self.file_path, 'w', encoding='utf-8') as f:
                # Write header
                for line in self.header.to_lines():
                    f.write(line + '\n')
                
                # Write entries
                for entry in entries:
                    f.write(entry.to_line() + '\n')
            
            logger.info(f"Wrote {len(entries)} entries to {self.file_path}")
            
        except Exception as e:
            logger.error(f"Error writing hash file {self.file_path}: {e}")
            raise
    
    def get_entries_by_hash(self, hash_value: str) -> List[HashEntry]:
        """Get all entries with the specified hash value"""
        return [entry for entry in self.entries if entry.primary_hash == hash_value]
    
    def get_entry_by_path(self, relative_path: str) -> Optional[HashEntry]:
        """Get entry by relative path"""
        for entry in self.entries:
            if entry.relative_path == relative_path:
                return entry
        return None
    
    def get_duplicates(self) -> Dict[str, List[HashEntry]]:
        """Find duplicate files (same hash value)"""
        hash_groups = {}
        
        for entry in self.entries:
            if not entry.is_symlink and not entry.is_comment:
                if entry.primary_hash not in hash_groups:
                    hash_groups[entry.primary_hash] = []
                hash_groups[entry.primary_hash].append(entry)
        
        # Return only groups with more than one file
        return {hash_val: entries for hash_val, entries in hash_groups.items() 
                if len(entries) > 1}
    
    def get_file_info_map(self) -> Dict[str, Tuple[int, float]]:
        """Get mapping of relative_path to (size, mtime) for update detection"""
        return {
            entry.relative_path: (entry.size, entry.mtime)
            for entry in self.entries
            if not entry.is_symlink and not entry.is_comment
        }
    
    @property
    def algorithm(self) -> Optional[HashAlgorithm]:
        """Get detected algorithm"""
        return self._algorithm
    
    def get_statistics(self) -> Dict:
        """Get hash file statistics"""
        total_files = len(self.entries)
        symlinks = sum(1 for entry in self.entries if entry.is_symlink)
        regular_files = total_files - symlinks
        total_size = sum(entry.size for entry in self.entries if not entry.is_symlink)
        
        duplicates = self.get_duplicates()
        duplicate_groups = len(duplicates)
        duplicate_files = sum(len(group) for group in duplicates.values())
        
        return {
            'total_entries': total_files,
            'regular_files': regular_files,
            'symlinks': symlinks,
            'total_size': total_size,
            'duplicate_groups': duplicate_groups,
            'duplicate_files': duplicate_files,
            'algorithm': self._algorithm.value if self._algorithm else 'unknown',
            'header': self.header
        }


def compare_hash_files(file1: HashFile, file2: HashFile) -> Dict:
    """
    Compare two hash files and find differences
    
    Args:
        file1: First hash file
        file2: Second hash file
    
    Returns:
        Dictionary with comparison results
    """
    # Create hash maps for efficient lookup
    hash_map1 = {entry.primary_hash: entry for entry in file1.entries 
                 if not entry.is_symlink and not entry.is_comment}
    hash_map2 = {entry.primary_hash: entry for entry in file2.entries 
                 if not entry.is_symlink and not entry.is_comment}
    
    # Find common hashes
    common_hashes = set(hash_map1.keys()) & set(hash_map2.keys())
    
    # Find files only in file1
    only_in_file1 = []
    for hash_val, entry in hash_map1.items():
        if hash_val not in hash_map2:
            only_in_file1.append(entry)
    
    # Find files only in file2
    only_in_file2 = []
    for hash_val, entry in hash_map2.items():
        if hash_val not in hash_map1:
            only_in_file2.append(entry)
    
    # Find matching files (same hash, different path)
    matching_hashes = []
    for hash_val in common_hashes:
        entry1 = hash_map1[hash_val]
        entry2 = hash_map2[hash_val]
        
        if entry1.relative_path != entry2.relative_path:
            matching_hashes.append({
                'hash': hash_val,
                'file1_path': entry1.relative_path,
                'file2_path': entry2.relative_path,
                'size': entry1.size
            })
    
    return {
        'common_hashes': len(common_hashes),
        'only_in_file1': only_in_file1,
        'only_in_file2': only_in_file2,
        'matching_hashes': matching_hashes,
        'total_file1': len(hash_map1),
        'total_file2': len(hash_map2)
    }
