"""
Hash file format handling with metadata headers and algorithm prefixes.
"""

import os
import socket
import getpass
from datetime import datetime
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass
from pathlib import Path

from .file_scanner import FileInfo
from .hash_algorithms import HashAlgorithm


@dataclass
class HashEntry:
    """Represents a single hash file entry."""
    metadata_hash: str
    file_hash: str
    directory: str
    filename: str
    size: int
    inode: int
    mtime: int
    algorithm: Optional[str] = None  # None for MD5 (backwards compatibility)


class HashFileWriter:
    """Handles writing hash files with proper format and metadata."""
    
    def __init__(self, output_path: str, algorithm: HashAlgorithm = HashAlgorithm.MD5):
        self.output_path = Path(output_path)
        self.algorithm = algorithm
        self._entries: List[HashEntry] = []
    
    def add_entry(self, file_info: FileInfo, metadata_hash: str, file_hash: str):
        """
        Add a hash entry for a file.
        
        Args:
            file_info: File information
            metadata_hash: Hash of file metadata
            file_hash: Hash of file content
        """
        # Split relative path into directory and filename
        relative_path = Path(file_info.relative_path)
        directory = str(relative_path.parent) if relative_path.parent != Path('.') else '.'
        filename = relative_path.name
        
        # Determine algorithm prefix
        algorithm_prefix = None if self.algorithm == HashAlgorithm.MD5 else self.algorithm.value.upper()
        
        entry = HashEntry(
            metadata_hash=metadata_hash,
            file_hash=file_hash,
            directory=directory,
            filename=filename,
            size=file_info.size,
            inode=file_info.inode,
            mtime=file_info.mtime,
            algorithm=algorithm_prefix
        )
        
        self._entries.append(entry)
    
    def add_symlink_entry(self, file_info: FileInfo):
        """
        Add a symlink entry as a commented line.
        
        Args:
            file_info: Symlink information
        """
        # Split relative path into directory and filename
        relative_path = Path(file_info.relative_path)
        directory = str(relative_path.parent) if relative_path.parent != Path('.') else '.'
        filename = relative_path.name
        
        entry = HashEntry(
            metadata_hash="SYMLINK",
            file_hash="",
            directory=directory,
            filename=filename,
            size=file_info.size,
            inode=file_info.inode,
            mtime=file_info.mtime,
            algorithm="SYMLINK"
        )
        
        self._entries.append(entry)
    
    def write_file(self, base_directory: str, append_mode: bool = False):
        """
        Write all entries to the hash file.
        
        Args:
            base_directory: Base directory that was scanned
            append_mode: If True, append to existing file; if False, create new file
        """
        # Create output directory if it doesn't exist
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        
        mode = 'a' if append_mode else 'w'
        with open(self.output_path, mode, encoding='utf-8') as f:
            # Write metadata header only if creating new file
            if not append_mode:
                self._write_header(f, base_directory)
            
            # Write hash entries
            for entry in self._entries:
                self._write_entry(f, entry)
    
    def write_header_only(self, base_directory: str):
        """
        Write only the metadata header to a new file.
        
        Args:
            base_directory: Base directory that was scanned
        """
        # Create output directory if it doesn't exist
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(self.output_path, 'w', encoding='utf-8') as f:
            # Write metadata header
            self._write_header(f, base_directory)
    
    def _write_header(self, file_handle, base_directory: str):
        """
        Write metadata header to hash file.
        
        Args:
            file_handle: Open file handle
            base_directory: Base directory that was scanned
        """
        # Get system information
        machine_name = socket.gethostname()
        username = getpass.getuser()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Write header lines
        file_handle.write(f"# Generated by filehasher v2.0.0\n")
        file_handle.write(f"# Machine: {machine_name}\n")
        file_handle.write(f"# Base directory: {os.path.abspath(base_directory)}\n")
        file_handle.write(f"# User: {username}\n")
        file_handle.write(f"# Generated: {timestamp}\n")
    
    def _write_entry(self, file_handle, entry: HashEntry):
        """
        Write a single hash entry to the file.
        
        Args:
            file_handle: Open file handle
            entry: Hash entry to write
        """
        if entry.algorithm == "SYMLINK":
            # Write symlink as commented line
            file_handle.write(f"# SYMLINK|{entry.directory}|{entry.filename}|{entry.size}|{entry.inode}|{entry.mtime}\n")
        else:
            # Format file hash with algorithm prefix if needed
            formatted_hash = entry.file_hash
            if entry.algorithm:
                formatted_hash = f"{entry.algorithm}:{entry.file_hash}"
            
            # Write regular hash entry
            file_handle.write(f"{entry.metadata_hash}|{formatted_hash}|{entry.directory}|{entry.filename}|{entry.size}|{entry.inode}|{entry.mtime}\n")


class HashFileReader:
    """Handles reading and parsing hash files."""
    
    def __init__(self, hash_file_path: str):
        self.hash_file_path = Path(hash_file_path)
        self._entries: List[HashEntry] = []
        self._metadata: Dict[str, str] = {}
    
    def read_file(self) -> Tuple[List[HashEntry], Dict[str, str]]:
        """
        Read and parse hash file.
        
        Returns:
            Tuple of (hash_entries, metadata)
        """
        if not self.hash_file_path.exists():
            raise FileNotFoundError(f"Hash file not found: {self.hash_file_path}")
        
        self._entries.clear()
        self._metadata.clear()
        
        with open(self.hash_file_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                
                if not line:
                    continue
                
                if line.startswith('#'):
                    # Parse metadata header
                    self._parse_metadata_line(line)
                else:
                    # Parse hash entry
                    try:
                        entry = self._parse_hash_line(line)
                        if entry:
                            self._entries.append(entry)
                    except ValueError as e:
                        print(f"Warning: Invalid hash entry at line {line_num}: {e}")
                        continue
        
        return self._entries.copy(), self._metadata.copy()
    
    def _parse_metadata_line(self, line: str):
        """
        Parse metadata header line.
        
        Args:
            line: Header line starting with '#'
        """
        if line.startswith('# Generated by'):
            self._metadata['version'] = line.split('by ')[1] if 'by ' in line else 'unknown'
        elif line.startswith('# Machine:'):
            self._metadata['machine'] = line.split(': ', 1)[1] if ': ' in line else 'unknown'
        elif line.startswith('# Base directory:'):
            self._metadata['base_directory'] = line.split(': ', 1)[1] if ': ' in line else 'unknown'
        elif line.startswith('# User:'):
            self._metadata['user'] = line.split(': ', 1)[1] if ': ' in line else 'unknown'
        elif line.startswith('# Generated:'):
            self._metadata['timestamp'] = line.split(': ', 1)[1] if ': ' in line else 'unknown'
        elif line.startswith('# SYMLINK|'):
            # Parse symlink entry
            parts = line[1:].split('|')  # Remove '#' and split
            if len(parts) >= 6:
                entry = HashEntry(
                    metadata_hash="SYMLINK",
                    file_hash="",
                    directory=parts[1],
                    filename=parts[2],
                    size=int(parts[3]),
                    inode=int(parts[4]),
                    mtime=int(parts[5]),
                    algorithm="SYMLINK"
                )
                self._entries.append(entry)
    
    def _parse_hash_line(self, line: str) -> Optional[HashEntry]:
        """
        Parse a hash entry line.
        
        Args:
            line: Hash entry line
            
        Returns:
            HashEntry object or None if invalid
        """
        parts = line.split('|')
        if len(parts) != 7:
            raise ValueError(f"Invalid hash entry format: expected 7 fields, got {len(parts)}")
        
        metadata_hash, file_hash, directory, filename, size, inode, mtime = parts
        
        # Parse algorithm from file hash
        algorithm = None
        if ':' in file_hash:
            algorithm, file_hash = file_hash.split(':', 1)
            algorithm = algorithm.lower()
        
        return HashEntry(
            metadata_hash=metadata_hash,
            file_hash=file_hash,
            directory=directory,
            filename=filename,
            size=int(size),
            inode=int(inode),
            mtime=int(mtime),
            algorithm=algorithm
        )
    
    def get_entries_by_hash(self) -> Dict[str, List[HashEntry]]:
        """
        Group entries by their file hash for duplicate detection.
        
        Returns:
            Dictionary mapping hash values to lists of entries
        """
        hash_groups = {}
        
        for entry in self._entries:
            if entry.algorithm == "SYMLINK":
                continue  # Skip symlinks
            
            if entry.file_hash not in hash_groups:
                hash_groups[entry.file_hash] = []
            
            hash_groups[entry.file_hash].append(entry)
        
        return hash_groups
    
    def get_duplicates(self) -> List[List[HashEntry]]:
        """
        Find duplicate files (same hash value).
        
        Returns:
            List of groups of duplicate entries
        """
        hash_groups = self.get_entries_by_hash()
        duplicates = []
        
        for hash_value, entries in hash_groups.items():
            if len(entries) > 1:
                duplicates.append(entries)
        
        return duplicates


def create_hash_file_writer(output_path: str, algorithm: HashAlgorithm = HashAlgorithm.MD5) -> HashFileWriter:
    """
    Create a hash file writer.
    
    Args:
        output_path: Path to output hash file
        algorithm: Hash algorithm to use
        
    Returns:
        HashFileWriter instance
    """
    return HashFileWriter(output_path, algorithm)


def read_hash_file(hash_file_path: str) -> Tuple[List[HashEntry], Dict[str, str]]:
    """
    Read and parse a hash file.
    
    Args:
        hash_file_path: Path to hash file
        
    Returns:
        Tuple of (hash_entries, metadata)
    """
    reader = HashFileReader(hash_file_path)
    return reader.read_file()