image: bradrydzewski/base

script:
  - sudo python setup.py install
  - filehasher -g
  - filehasher -u
  - filehasher -c .hashes .hashes

publish:
    pypi:
        username: {{username}}
        password: {{password}}
